/**
 * iconMap.jsx — maps icon_name strings (stored in DB) to Ant Design icon components.
 * Used by the dynamic sidebar to resolve icons from backend menu data.
 */

import React from 'react'
import {
  ApiOutlined,
  AppstoreAddOutlined,
  AppstoreOutlined,
  AuditOutlined,
  BarChartOutlined,
  BankOutlined,
  BellOutlined,
  BlockOutlined,
  BookOutlined,
  BranchesOutlined,
  BugOutlined,
  CalendarOutlined,
  CheckSquareOutlined,
  ClusterOutlined,
  ContainerOutlined,
  CreditCardOutlined,
  CrownOutlined,
  CustomerServiceOutlined,
  DashboardOutlined,
  DatabaseOutlined,
  DesktopOutlined,
  DollarOutlined,
  ExceptionOutlined,
  FileOutlined,
  FileProtectOutlined,
  FileSearchOutlined,
  FileTextOutlined,
  FolderOutlined,
  FormOutlined,
  FundOutlined,
  GlobalOutlined,
  IdcardOutlined,
  LockOutlined,
  MonitorOutlined,
  NotificationOutlined,
  OrderedListOutlined,
  PhoneOutlined,
  PieChartOutlined,
  ReconciliationOutlined,
  RetweetOutlined,
  RiseOutlined,
  SafetyOutlined,
  ScheduleOutlined,
  SendOutlined,
  SettingOutlined,
  ShopOutlined,
  SlidersOutlined,
  StopOutlined,
  SyncOutlined,
  TagOutlined,
  TagsOutlined,
  TeamOutlined,
  ToolOutlined,
  TransactionOutlined,
} from '@ant-design/icons'

const iconMap = {
  ApiOutlined: <ApiOutlined />,
  AppstoreAddOutlined: <AppstoreAddOutlined />,
  AppstoreOutlined: <AppstoreOutlined />,
  AuditOutlined: <AuditOutlined />,
  BarChartOutlined: <BarChartOutlined />,
  BankOutlined: <BankOutlined />,
  BellOutlined: <BellOutlined />,
  BlockOutlined: <BlockOutlined />,
  BookOutlined: <BookOutlined />,
  BranchesOutlined: <BranchesOutlined />,
  BugOutlined: <BugOutlined />,
  CalendarOutlined: <CalendarOutlined />,
  CheckSquareOutlined: <CheckSquareOutlined />,
  ClusterOutlined: <ClusterOutlined />,
  ContainerOutlined: <ContainerOutlined />,
  CreditCardOutlined: <CreditCardOutlined />,
  CrownOutlined: <CrownOutlined />,
  CustomerServiceOutlined: <CustomerServiceOutlined />,
  DashboardOutlined: <DashboardOutlined />,
  DatabaseOutlined: <DatabaseOutlined />,
  DesktopOutlined: <DesktopOutlined />,
  DollarOutlined: <DollarOutlined />,
  ExceptionOutlined: <ExceptionOutlined />,
  FileOutlined: <FileOutlined />,
  FileProtectOutlined: <FileProtectOutlined />,
  FileSearchOutlined: <FileSearchOutlined />,
  FileTextOutlined: <FileTextOutlined />,
  FolderOutlined: <FolderOutlined />,
  FormOutlined: <FormOutlined />,
  FundOutlined: <FundOutlined />,
  GlobalOutlined: <GlobalOutlined />,
  IdcardOutlined: <IdcardOutlined />,
  LockOutlined: <LockOutlined />,
  MonitorOutlined: <MonitorOutlined />,
  NotificationOutlined: <NotificationOutlined />,
  OrderedListOutlined: <OrderedListOutlined />,
  PhoneOutlined: <PhoneOutlined />,
  PieChartOutlined: <PieChartOutlined />,
  ReconciliationOutlined: <ReconciliationOutlined />,
  RetweetOutlined: <RetweetOutlined />,
  RiseOutlined: <RiseOutlined />,
  SafetyOutlined: <SafetyOutlined />,
  ScheduleOutlined: <ScheduleOutlined />,
  SendOutlined: <SendOutlined />,
  SettingOutlined: <SettingOutlined />,
  ShopOutlined: <ShopOutlined />,
  SlidersOutlined: <SlidersOutlined />,
  StopOutlined: <StopOutlined />,
  SyncOutlined: <SyncOutlined />,
  TagOutlined: <TagOutlined />,
  TagsOutlined: <TagsOutlined />,
  TeamOutlined: <TeamOutlined />,
  ToolOutlined: <ToolOutlined />,
  TransactionOutlined: <TransactionOutlined />,
}

/**
 * Resolve an icon component by its string name.
 * Returns null if the name is not registered.
 * @param {string} name
 * @returns {React.ReactElement|null}
 */
export const getIcon = (name) => iconMap[name] ?? null

export default iconMap
